version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: balanceiq_backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app
    environment:
      - CORS_ORIGINS=["http://localhost", "http://localhost:80", "http://localhost:5173"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: balanceiq_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
